name : Deployment Test
on : 
  pull_request:
    types: opened
    branches : 
      - main
      - 'dev-*' # dev-new, dev-add-new
      - 'feat/**' #feat/new fet/new/button
  workflow_dispatch:    
  push : 
    branches : 
      - main
      - 'dev-*' # dev-new, dev-add-new
      - 'feat/**' #feat/new fet/new/button
    paths-ignore:
      - '.github/workflows/*'
jobs: 
  deploy :
    needs : test
    runs-on : ubuntu-20.04  
    steps :    
      - name : Get Code
        uses: actions/checkout@v4    
      - name : Install dependacies
        run : npm ci 
      - name : Build Project
        run : npm run build   
      - name : Deploy
        run : echo "Deploying..."           